//! Observational illuminant estimation (C5, "cross-camera colour constancy").
//!
//! This module answers a question the rest of the pipeline never asks: what
//! light was the scene under? It is observational only — nothing here touches
//! exposure, tone, colour or output pixels, and with `--illuminant` off not a
//! single byte of a sidecar moves. The estimate is recorded so the corpus can
//! be measured against the camera's own as-shot neutral before any renderer is
//! allowed to depend on it.
//!
//! Two halves, split at the point where the upstream implementation stops being
//! expressible as an ONNX graph:
//!
//! 1. The neural half — encoder, bottleneck and the two decoders that emit a
//!    convolutional-colour-constancy filter `F` and bias `B` — lives in
//!    `models/artifacts/c5_m7_h64.onnx` and runs through lege-gpu.
//! 2. The application half — circular convolution of the histogram with `F`,
//!    the bias, a softmax over the whole 64x64 grid and a soft-argmax back to a
//!    log-chroma pair — is owned here. Upstream does it with FFTs, which the
//!    ONNX bridge rejects; on a 64x64 grid it is cheap, and keeping it in Rust
//!    means the post-processing is exactly as deterministic as the rest of the
//!    render path.
//!
//! Everything the histogram builder does is transcribed from upstream's
//! `ops.py`; `tests/fixtures/c5/README.md` carries the derivation, and
//! `tests/c5_golden.rs` pins each stage against fixtures generated by the
//! Python port.
//!
//! The graph is run on the CPU deliberately. Its in-graph `m = 7` frame
//! duplication produces rank-5 intermediates, which the wgpu compiler has no
//! coverage for; a wrong answer there would look like a plausible illuminant
//! rather than an error, so the GPU path is not offered at all.

use crate::types::{CameraRgb, Image};
use anyhow::{Context, Result, ensure};
use rawler::RawImage;
use serde::Serialize;
use std::path::Path;

/// Histogram grid edge, in bins. The exported graph is stamped for this size.
pub const HIST_SIZE: usize = 64;
/// Proxy width handed to the histogram builder.
pub const PROXY_WIDTH: usize = 384;
/// Proxy height handed to the histogram builder.
pub const PROXY_HEIGHT: usize = 256;
/// Log-chroma range the histogram spans, `[-HIST_BOUNDARY, +HIST_BOUNDARY]`.
pub const HIST_BOUNDARY: f64 = 2.85;
/// File name of the exported C5 graph inside the model directory.
pub const MODEL_FILE: &str = "c5_m7_h64.onnx";
/// Frozen name for this estimator's behaviour, recorded per frame.
pub const ILLUMINANT_VERSION: &str = "c5-m7-h64-v1";

const PLANE: usize = HIST_SIZE * HIST_SIZE;
/// Upstream's `EPS`, used both to reject empty pixels and to keep the
/// histogram normalization finite.
const EPS: f64 = 1.0e-9;

/// Pre-white-balance camera RGB, downsampled to the size C5 was trained on.
///
/// Camera space is the point: C5 estimates the illuminant *as the sensor saw
/// it*, so anything applied after the black/white normalization — white
/// balance above all — would be estimating the illuminant of an image that has
/// already had the illuminant removed. The buffer is deliberately not an
/// [`Image<CameraRgb>`]: it is a fixed-size analysis input, not a stage of the
/// render, and it is never converted onward.
#[derive(Debug, Clone)]
pub struct CameraProxy {
    pub width: usize,
    pub height: usize,
    /// Row-major, `width * height` triplets, nominally in `[0, 1]`.
    pub rgb: Vec<[f32; 3]>,
    pub source_width: usize,
    pub source_height: usize,
}

/// What the proxy was, recorded alongside the estimate.
#[derive(Debug, Clone, Serialize)]
pub struct CameraProxyInfo {
    pub width: usize,
    pub height: usize,
    pub source_width: usize,
    pub source_height: usize,
    pub rendering: &'static str,
}

impl From<&CameraProxy> for CameraProxyInfo {
    fn from(proxy: &CameraProxy) -> Self {
        Self {
            width: proxy.width,
            height: proxy.height,
            source_width: proxy.source_width,
            source_height: proxy.source_height,
            rendering: "pre-white-balance-camera-rgb-v1",
        }
    }
}

/// One frame's illuminant estimate, or the reason there is not one.
///
/// Observational only. No field of this struct is read by the tone controller,
/// the colour transform or the encoder-hints contract; it exists to be measured
/// against the camera's own as-shot neutral over a corpus.
#[derive(Debug, Clone, Serialize)]
pub struct IlluminantEvidence {
    /// Frozen behaviour name, so a corpus survey can tell two estimators apart.
    pub version: &'static str,
    /// Estimated illuminant in camera space, unit L2 norm. `None` when
    /// inference failed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub camera_rgb: Option<[f32; 3]>,
    /// The same illuminant as CIE 1931 `xy`, through the file's own
    /// XYZ-to-camera calibration matrix.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub xy: Option<[f64; 2]>,
    /// Correlated colour temperature of `xy`, by Robertson's method.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cct_k: Option<f64>,
    /// Signed distance from the Planckian locus in CIE 1960 `uv`; positive is
    /// above the locus (green), negative below (magenta).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duv: Option<f64>,
    /// Angular error, in degrees, between the estimate and the camera's own
    /// as-shot neutral in camera space. This is the number the corpus survey
    /// is for: a value near zero on every frame would mean the estimator is
    /// reading back the white balance rather than the scene.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub as_shot_angular_error_deg: Option<f32>,
    /// Which calibration illuminant's matrix took camera space to XYZ.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub matrix_source: Option<String>,
    pub proxy: CameraProxyInfo,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<crate::scene::ModelProvenance>,
    /// Which backend actually ran the graph. Always the CPU reference; see the
    /// module comment for why the GPU path is not offered.
    pub backend: &'static str,
    /// Why there is no estimate, when there is not one. A missing model file
    /// or an unsupported graph is evidence, not a render error.
    pub inference_errors: Vec<String>,
}

/// Downsample pre-white-balance camera RGB to the fixed C5 proxy size.
///
/// Aspect ratio is deliberately not preserved: upstream trains and evaluates on
/// `cv2.resize(image, [384, 256])`, which stretches, and a letterboxed proxy
/// would put the model outside its training distribution for the sake of a
/// geometric tidiness the histogram cannot even see (a log-chroma histogram is
/// invariant to where a pixel is, so it is also invariant to orientation —
/// which is why this runs before the orientation step without caring).
pub fn build_camera_proxy(image: &Image<CameraRgb>) -> Result<CameraProxy> {
    ensure!(
        image.width > 0 && image.height > 0,
        "cannot build an illuminant proxy from a {}x{} image",
        image.width,
        image.height
    );
    let mut rgb = vec![[0.0_f32; 3]; PROXY_WIDTH * PROXY_HEIGHT];
    let x_scale = image.width as f32 / PROXY_WIDTH as f32;
    let y_scale = image.height as f32 / PROXY_HEIGHT as f32;

    for y in 0..PROXY_HEIGHT {
        // The half-pixel offsets are `cv2.resize`'s own INTER_LINEAR mapping,
        // so the proxy matches the fixtures the Python port generated.
        let sy = ((y as f32 + 0.5) * y_scale - 0.5).clamp(0.0, (image.height - 1) as f32);
        for x in 0..PROXY_WIDTH {
            let sx = ((x as f32 + 0.5) * x_scale - 0.5).clamp(0.0, (image.width - 1) as f32);
            rgb[y * PROXY_WIDTH + x] = bilinear(image, sx, sy);
        }
    }

    Ok(CameraProxy {
        width: PROXY_WIDTH,
        height: PROXY_HEIGHT,
        rgb,
        source_width: image.width,
        source_height: image.height,
    })
}

fn bilinear(image: &Image<CameraRgb>, x: f32, y: f32) -> [f32; 3] {
    let x0 = x.floor() as usize;
    let y0 = y.floor() as usize;
    let x1 = (x0 + 1).min(image.width - 1);
    let y1 = (y0 + 1).min(image.height - 1);
    let fx = x - x0 as f32;
    let fy = y - y0 as f32;

    let at = |px: usize, py: usize| image.pixels[py * image.width + px];
    let (p00, p10, p01, p11) = (at(x0, y0), at(x1, y0), at(x0, y1), at(x1, y1));

    let mut out = [0.0_f32; 3];
    for channel in 0..3 {
        let top = p00[channel] + (p10[channel] - p00[channel]) * fx;
        let bottom = p01[channel] + (p11[channel] - p01[channel]) * fx;
        out[channel] = top + (bottom - top) * fy;
    }
    out
}

/// Build the model's `chroma_histograms` input: 4 planes of 64x64, CHW.
///
/// Channel 0 is the log-chroma histogram of the proxy, channel 1 the same
/// histogram of its edge image, and channels 2 and 3 the normalized `u` and `v`
/// coordinate grids the network uses as a positional encoding.
///
/// Accumulation is sequential and in `f64`, in raster order: this runs inside
/// a `--jobs N` batch, and a histogram bin summed in thread-scheduling order
/// would make the estimate depend on batch composition.
pub fn histogram_stack(proxy: &CameraProxy) -> Vec<f32> {
    let mut stack = vec![0.0_f32; 4 * PLANE];

    let pixels: Vec<[f64; 3]> = proxy
        .rgb
        .iter()
        .map(|pixel| [pixel[0] as f64, pixel[1] as f64, pixel[2] as f64])
        .collect();
    accumulate_histogram(&pixels, &mut stack[..PLANE]);
    accumulate_histogram(
        &edge_image(proxy.width, proxy.height, &pixels),
        &mut stack[PLANE..2 * PLANE],
    );

    // `get_uv_coord(normalize=True)`: `u` ascends left to right, `v` descends
    // top to bottom, both mapped onto [0, 1].
    let last = (HIST_SIZE - 1) as f32;
    for row in 0..HIST_SIZE {
        for column in 0..HIST_SIZE {
            stack[2 * PLANE + row * HIST_SIZE + column] = column as f32 / last;
            stack[3 * PLANE + row * HIST_SIZE + column] = (last - row as f32) / last;
        }
    }
    stack
}

/// Bin centre spacing: the boundary spans `nbins - 1` steps, not `nbins`.
fn bin_step() -> f64 {
    2.0 * HIST_BOUNDARY / (HIST_SIZE - 1) as f64
}

/// `compute_histogram`'s box soft-binning, followed by its sqrt normalization.
fn accumulate_histogram(pixels: &[[f64; 3]], out: &mut [f32]) {
    let step = bin_step();
    let mut bins = vec![0.0_f64; PLANE];

    // At most three bin centres lie within `step` of any value, so the search
    // is a short scan around the nearest index rather than a 64-wide sweep.
    let mut columns = [0_usize; 3];
    let mut rows = [0_usize; 3];

    for pixel in pixels {
        let (r, g, b) = (pixel[0], pixel[1], pixel[2]);
        if r + g + b <= EPS {
            continue;
        }
        let weight = (r * r + g * g + b * b).sqrt();
        let u = (g + EPS).ln() - (r + EPS).ln();
        let v = (g + EPS).ln() - (b + EPS).ln();

        let column_count = touched_bins(u, step, &mut columns);
        if column_count == 0 {
            continue;
        }
        // `A_v` is `A_u` flipped, so a row index is the mirror of the column
        // index the same value would have taken.
        let row_count = touched_bins(v, step, &mut rows);
        for row in &rows[..row_count] {
            let base = (HIST_SIZE - 1 - row) * HIST_SIZE;
            for column in &columns[..column_count] {
                bins[base + column] += weight;
            }
        }
    }

    let total: f64 = bins.iter().sum();
    let scale = 1.0 / (total + EPS);
    for (bin, cell) in bins.iter().zip(out.iter_mut()) {
        *cell = (bin * scale).sqrt() as f32;
    }
}

/// Indices whose bin centre is within `step` of `value`, excluding an exact
/// coincidence.
///
/// The exclusion is upstream's, not a rounding guard: `compute_histogram`
/// keeps only survivors with a non-zero distance, so a value landing exactly on
/// a centre increments neither neighbour. It is vanishingly rare with
/// continuous log-chroma, and reproducing it is cheaper than explaining a
/// one-bin divergence later.
fn touched_bins(value: f64, step: f64, out: &mut [usize; 3]) -> usize {
    let position = (value + HIST_BOUNDARY) / step;
    let first = position.floor() as i64 - 1;
    let mut count = 0;
    for index in first..=first + 2 {
        if index < 0 || index >= HIST_SIZE as i64 {
            continue;
        }
        let centre = -HIST_BOUNDARY + index as f64 * step;
        let distance = (value - centre).abs();
        if distance > 0.0 && distance <= step {
            out[count] = index as usize;
            count += 1;
            if count == 3 {
                break;
            }
        }
    }
    count
}

/// `compute_edges`: mean absolute difference to the 8-connected neighbourhood.
///
/// Upstream reflect-pads by one pixel first. At a one-pixel border, reflection
/// maps index `-1` to `0` and `H` to `H - 1`, so it is exactly edge clamping —
/// written that way here rather than materializing a padded copy.
fn edge_image(width: usize, height: usize, pixels: &[[f64; 3]]) -> Vec<[f64; 3]> {
    let mut edges = vec![[0.0_f64; 3]; width * height];

    for y in 0..height {
        for x in 0..width {
            let centre = pixels[y * width + x];
            let mut sums = [0.0_f64; 3];
            for dy in -1_i64..=1 {
                for dx in -1_i64..=1 {
                    if dx == 0 && dy == 0 {
                        continue;
                    }
                    let ny = (y as i64 + dy).clamp(0, height as i64 - 1) as usize;
                    let nx = (x as i64 + dx).clamp(0, width as i64 - 1) as usize;
                    let neighbour = pixels[ny * width + nx];
                    for channel in 0..3 {
                        sums[channel] += (centre[channel] - neighbour[channel]).abs();
                    }
                }
            }
            edges[y * width + x] = [sums[0] / 8.0, sums[1] / 8.0, sums[2] / 8.0];
        }
    }
    edges
}

/// Apply the predicted convolutional-colour-constancy filter and bias.
///
/// `hist` is the model input stack (only its first two planes, the chroma and
/// edge histograms, are read), `filter` is `ccc_filter` as 2x64x64 and `bias`
/// is `ccc_bias` as 64x64, both with the batch axis already stripped.
///
/// Returns the illuminant in camera RGB, unit L2 norm.
pub fn apply_ccc(hist: &[f32], filter: &[f32], bias: &[f32]) -> Result<[f32; 3]> {
    ensure!(
        hist.len() >= 2 * PLANE && filter.len() >= 2 * PLANE && bias.len() >= PLANE,
        "C5 post-processing needs 2 histogram planes, 2 filter planes and a bias plane, got \
         {}/{}/{} values",
        hist.len(),
        filter.len(),
        bias.len()
    );

    // Circular convolution through the convolution theorem, exactly as
    // upstream's `rfft2 * rfft2 -> irfft2` does it: the filter is defined on
    // the wrapped grid, so a windowed convolution would be a different
    // operator, not an approximation of this one.
    let mut accumulated_re = vec![0.0_f64; PLANE];
    let mut accumulated_im = vec![0.0_f64; PLANE];
    for channel in 0..2 {
        let (mut hist_re, mut hist_im) = plane_to_complex(&hist[channel * PLANE..]);
        let (mut filter_re, mut filter_im) = plane_to_complex(&filter[channel * PLANE..]);
        fft2(&mut hist_re, &mut hist_im, false);
        fft2(&mut filter_re, &mut filter_im, false);
        for index in 0..PLANE {
            accumulated_re[index] +=
                hist_re[index] * filter_re[index] - hist_im[index] * filter_im[index];
            accumulated_im[index] +=
                hist_re[index] * filter_im[index] + hist_im[index] * filter_re[index];
        }
    }
    fft2(&mut accumulated_re, &mut accumulated_im, true);

    let mut heat = vec![0.0_f64; PLANE];
    for index in 0..PLANE {
        heat[index] = (accumulated_re[index] + bias[index] as f64).clamp(-100.0, 100.0);
    }

    // Softmax over the whole flattened grid, then a soft-argmax against the
    // *unnormalized* coordinate grids — the network's positional encoding is
    // normalized, its output expectation is not.
    let maximum = heat.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    let mut total = 0.0_f64;
    for cell in heat.iter_mut() {
        *cell = (*cell - maximum).exp();
        total += *cell;
    }

    let half = (HIST_SIZE - 1) as f64 / 2.0;
    let mut u = 0.0_f64;
    let mut v = 0.0_f64;
    for row in 0..HIST_SIZE {
        for column in 0..HIST_SIZE {
            let probability = heat[row * HIST_SIZE + column] / total;
            u += probability * (column as f64 - half);
            v += probability * (half - row as f64);
        }
    }

    // `from_coord_to_uv` divides the span by `hist_size`, not `hist_size - 1`.
    // The asymmetry with the bin-centre spacing is upstream's and is load
    // bearing: changing it moves the estimate by a visible fraction of a bin.
    let scale = 2.0 * HIST_BOUNDARY / HIST_SIZE as f64;
    Ok(uv_to_rgb(u * scale, v * scale))
}

/// `uv_to_rgb`: undo the log-chroma ratios and normalize to a unit vector.
fn uv_to_rgb(u: f64, v: f64) -> [f32; 3] {
    let rgb = [(-u).exp(), 1.0, (-v).exp()];
    let norm = (rgb[0] * rgb[0] + rgb[1] * rgb[1] + rgb[2] * rgb[2]).sqrt();
    [
        (rgb[0] / norm) as f32,
        (rgb[1] / norm) as f32,
        (rgb[2] / norm) as f32,
    ]
}

fn plane_to_complex(plane: &[f32]) -> (Vec<f64>, Vec<f64>) {
    (
        plane[..PLANE].iter().map(|value| *value as f64).collect(),
        vec![0.0_f64; PLANE],
    )
}

/// Separable 64x64 complex FFT: rows, then columns.
///
/// Hand-rolled rather than pulled in as a dependency. At this size the whole
/// transform is a few microseconds, a general FFT crate would be several
/// thousand lines for one call site, and a fixed radix-2 kernel is trivially
/// deterministic — which a runtime-planned FFT, which may pick a different
/// algorithm per machine, is not.
fn fft2(re: &mut [f64], im: &mut [f64], inverse: bool) {
    let mut row_re = [0.0_f64; HIST_SIZE];
    let mut row_im = [0.0_f64; HIST_SIZE];

    for row in 0..HIST_SIZE {
        let base = row * HIST_SIZE;
        row_re.copy_from_slice(&re[base..base + HIST_SIZE]);
        row_im.copy_from_slice(&im[base..base + HIST_SIZE]);
        fft(&mut row_re, &mut row_im, inverse);
        re[base..base + HIST_SIZE].copy_from_slice(&row_re);
        im[base..base + HIST_SIZE].copy_from_slice(&row_im);
    }

    for column in 0..HIST_SIZE {
        for row in 0..HIST_SIZE {
            row_re[row] = re[row * HIST_SIZE + column];
            row_im[row] = im[row * HIST_SIZE + column];
        }
        fft(&mut row_re, &mut row_im, inverse);
        for row in 0..HIST_SIZE {
            re[row * HIST_SIZE + column] = row_re[row];
            im[row * HIST_SIZE + column] = row_im[row];
        }
    }
}

/// `(cos, sin)` of `-2*pi*k / HIST_SIZE`, or its conjugate for the inverse.
///
/// Tabulated on first use rather than recomputed: a 64x64 transform asks for
/// this 24,576 times per `apply_ccc`, and the `sin_cos` calls were most of the
/// cost. The table is the same values in the same order on every machine, so
/// nothing about determinism changes.
fn twiddle(index: usize, inverse: bool) -> (f64, f64) {
    use std::sync::OnceLock;
    static TABLE: OnceLock<[(f64, f64); HIST_SIZE / 2]> = OnceLock::new();
    let table = TABLE.get_or_init(|| {
        let mut table = [(0.0_f64, 0.0_f64); HIST_SIZE / 2];
        for (index, entry) in table.iter_mut().enumerate() {
            let theta = -std::f64::consts::TAU * index as f64 / HIST_SIZE as f64;
            let (sin, cos) = theta.sin_cos();
            *entry = (cos, sin);
        }
        table
    });
    let (cos, sin) = table[index];
    if inverse { (cos, -sin) } else { (cos, sin) }
}

/// In-place iterative radix-2 FFT over exactly [`HIST_SIZE`] points.
///
/// The inverse form divides by `HIST_SIZE`, so a forward and an inverse pass
/// round-trip; applied separably that gives the usual `1 / n^2` for the 2D
/// transform without a separate scaling pass.
fn fft(re: &mut [f64; HIST_SIZE], im: &mut [f64; HIST_SIZE], inverse: bool) {
    const BITS: u32 = HIST_SIZE.trailing_zeros();

    for index in 0..HIST_SIZE {
        let reversed = (index as u32).reverse_bits() >> (32 - BITS);
        let reversed = reversed as usize;
        if reversed > index {
            re.swap(index, reversed);
            im.swap(index, reversed);
        }
    }

    let mut length = 2;
    while length <= HIST_SIZE {
        let stride = HIST_SIZE / length;
        for start in (0..HIST_SIZE).step_by(length) {
            for offset in 0..length / 2 {
                let (cos, sin) = twiddle(offset * stride, inverse);
                let even = start + offset;
                let odd = even + length / 2;
                let product_re = re[odd] * cos - im[odd] * sin;
                let product_im = re[odd] * sin + im[odd] * cos;
                re[odd] = re[even] - product_re;
                im[odd] = im[even] - product_im;
                re[even] += product_re;
                im[even] += product_im;
            }
        }
        length <<= 1;
    }

    if inverse {
        let scale = 1.0 / HIST_SIZE as f64;
        for index in 0..HIST_SIZE {
            re[index] *= scale;
            im[index] *= scale;
        }
    }
}

/// Estimate the illuminant for one frame.
///
/// Infallible by construction: a missing model file, an unsupported graph or a
/// file with no usable calibration matrix produces evidence explaining itself,
/// never a failed render. That is the same rule [`crate::scene::observe`]
/// follows for inference, applied one level higher because nothing downstream
/// consumes this yet — there is no controller decision left to preserve, so
/// there is no reason for any failure here to reach the caller at all.
pub fn observe(proxy: &CameraProxy, raw: &RawImage, model_dir: &Path) -> IlluminantEvidence {
    let mut evidence = IlluminantEvidence {
        version: ILLUMINANT_VERSION,
        camera_rgb: None,
        xy: None,
        cct_k: None,
        duv: None,
        as_shot_angular_error_deg: None,
        matrix_source: None,
        proxy: CameraProxyInfo::from(proxy),
        model: None,
        backend: "lege-gpu-cpu-reference",
        inference_errors: Vec::new(),
    };

    let stack = histogram_stack(proxy);
    let camera_rgb = match infer(&stack, model_dir) {
        Ok((rgb, provenance)) => {
            evidence.model = Some(provenance);
            rgb
        }
        Err(error) => {
            evidence.inference_errors.push(format!("c5: {error:#}"));
            return evidence;
        }
    };
    evidence.camera_rgb = Some(camera_rgb);

    match crate::color::camera_to_xyz(raw) {
        Some((illuminant, camera_to_xyz)) => {
            evidence.matrix_source = Some(format!("{illuminant:?}"));
            let xyz = [
                camera_to_xyz[0][0] * camera_rgb[0]
                    + camera_to_xyz[0][1] * camera_rgb[1]
                    + camera_to_xyz[0][2] * camera_rgb[2],
                camera_to_xyz[1][0] * camera_rgb[0]
                    + camera_to_xyz[1][1] * camera_rgb[1]
                    + camera_to_xyz[1][2] * camera_rgb[2],
                camera_to_xyz[2][0] * camera_rgb[0]
                    + camera_to_xyz[2][1] * camera_rgb[1]
                    + camera_to_xyz[2][2] * camera_rgb[2],
            ];
            let xyz = [xyz[0] as f64, xyz[1] as f64, xyz[2] as f64];
            match crate::dngcolor::chromaticity(&xyz) {
                Some((x, y)) => {
                    evidence.xy = Some([x, y]);
                    if let Some((cct, duv)) = crate::dngcolor::temperature_and_duv(x, y) {
                        evidence.cct_k = Some(cct);
                        evidence.duv = Some(duv);
                    } else {
                        evidence
                            .inference_errors
                            .push("no correlated colour temperature for the estimated xy".into());
                    }
                }
                None => evidence
                    .inference_errors
                    .push("the estimated illuminant left the visible chromaticity diagram".into()),
            }
        }
        None => evidence
            .inference_errors
            .push("the file carries no usable XYZ-to-camera calibration matrix".into()),
    }

    match as_shot_neutral(raw) {
        Some(neutral) => {
            evidence.as_shot_angular_error_deg = Some(angular_error_deg(camera_rgb, neutral));
        }
        None => evidence
            .inference_errors
            .push("the file recorded no as-shot white balance to compare against".into()),
    }

    evidence
}

/// The camera's own neutral in camera space: the reciprocal of the as-shot
/// white-balance multipliers, normalized.
///
/// The multipliers are what the render applies to *remove* the illuminant
/// ([`crate::color::ColorTransform::convert3`]), so their reciprocal is the
/// colour the camera believes the light was — the like-for-like comparison to
/// C5's estimate.
fn as_shot_neutral(raw: &RawImage) -> Option<[f32; 3]> {
    if raw.wb_coeffs[0].is_nan() {
        return None;
    }
    let mut neutral = [0.0_f32; 3];
    for (channel, cell) in neutral.iter_mut().enumerate() {
        let coefficient = raw.wb_coeffs[channel];
        if !coefficient.is_finite() || coefficient <= 0.0 {
            return None;
        }
        *cell = 1.0 / coefficient;
    }
    let norm = (neutral[0] * neutral[0] + neutral[1] * neutral[1] + neutral[2] * neutral[2]).sqrt();
    if !norm.is_finite() || norm <= 0.0 {
        return None;
    }
    Some([neutral[0] / norm, neutral[1] / norm, neutral[2] / norm])
}

/// Angle between two colours read as vectors, the standard colour-constancy
/// error measure.
fn angular_error_deg(a: [f32; 3], b: [f32; 3]) -> f32 {
    let dot = (a[0] * b[0] + a[1] * b[1] + a[2] * b[2]) as f64;
    let norm_a = ((a[0] * a[0] + a[1] * a[1] + a[2] * a[2]) as f64).sqrt();
    let norm_b = ((b[0] * b[0] + b[1] * b[1] + b[2] * b[2]) as f64).sqrt();
    let cosine = (dot / (norm_a * norm_b + 1.0e-12)).clamp(-1.0, 1.0);
    cosine.acos().to_degrees() as f32
}

/// Run the graph and apply its filter and bias.
fn infer(stack: &[f32], model_dir: &Path) -> Result<([f32; 3], crate::scene::ModelProvenance)> {
    use lege_gpu::vision::{OnnxSession, Tensor};

    let path = model_dir.join(MODEL_FILE);
    let session = OnnxSession::from_path(&path)?;
    let input = Tensor::new(vec![1, 4, HIST_SIZE, HIST_SIZE], stack.to_vec())?;
    // CPU only, and not as a fallback: see the module comment on rank-5
    // intermediates.
    let outputs = session.run_cpu(&input)?;
    let provenance = crate::scene::model_provenance(
        &path,
        "c5-illuminant",
        "camera-rgb-log-chroma-histogram-v1",
        "lege-gpu-cpu-reference",
        &session,
    )?;

    let filter = outputs
        .get("ccc_filter")
        .context("C5 did not return ccc_filter")?;
    let bias = outputs
        .get("ccc_bias")
        .context("C5 did not return ccc_bias")?;
    ensure!(
        filter.shape == [1, 2, HIST_SIZE, HIST_SIZE],
        "unexpected ccc_filter shape {:?}",
        filter.shape
    );
    ensure!(
        bias.shape == [1, HIST_SIZE, HIST_SIZE],
        "unexpected ccc_bias shape {:?}",
        bias.shape
    );

    let rgb = apply_ccc(stack, &filter.data, &bias.data)?;
    Ok((rgb, provenance))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn coordinate_planes_span_the_unit_interval() {
        let proxy = CameraProxy {
            width: 2,
            height: 2,
            rgb: vec![[0.5, 0.5, 0.5]; 4],
            source_width: 2,
            source_height: 2,
        };
        let stack = histogram_stack(&proxy);
        // `u` ascends with the column, `v` descends with the row.
        assert_eq!(stack[2 * PLANE], 0.0);
        assert_eq!(stack[2 * PLANE + HIST_SIZE - 1], 1.0);
        assert_eq!(stack[3 * PLANE], 1.0);
        assert_eq!(stack[3 * PLANE + (HIST_SIZE - 1) * HIST_SIZE], 0.0);
    }

    #[test]
    fn a_neutral_frame_lands_on_the_middle_bin() {
        // Every pixel has u = v = 0, which falls between bins 31 and 32 and
        // therefore straddles both in each axis.
        let proxy = CameraProxy {
            width: 4,
            height: 4,
            rgb: vec![[0.4, 0.4, 0.4]; 16],
            source_width: 4,
            source_height: 4,
        };
        let stack = histogram_stack(&proxy);
        let occupied: Vec<usize> = (0..PLANE).filter(|index| stack[*index] > 0.0).collect();
        assert_eq!(
            occupied,
            vec![
                31 * HIST_SIZE + 31,
                31 * HIST_SIZE + 32,
                32 * HIST_SIZE + 31,
                32 * HIST_SIZE + 32
            ]
        );
        let energy: f32 = occupied.iter().map(|index| stack[*index].powi(2)).sum();
        assert!((energy - 1.0).abs() < 1.0e-5, "normalization lost energy");
    }

    #[test]
    fn the_fft_round_trips() {
        let mut re: Vec<f64> = (0..PLANE).map(|index| (index % 13) as f64).collect();
        let mut im = vec![0.0_f64; PLANE];
        let original = re.clone();
        fft2(&mut re, &mut im, false);
        fft2(&mut re, &mut im, true);
        for (value, expected) in re.iter().zip(original.iter()) {
            assert!((value - expected).abs() < 1.0e-9);
        }
    }

    #[test]
    fn a_delta_filter_convolves_to_the_histogram_itself() {
        // A unit impulse at the origin is the identity for circular
        // convolution, so the heat map is the first histogram plane and the
        // soft-argmax has to agree with a direct softmax over it.
        let mut hist = vec![0.0_f32; 2 * PLANE];
        hist[10 * HIST_SIZE + 20] = 1.0;
        let mut filter = vec![0.0_f32; 2 * PLANE];
        filter[0] = 1.0;
        let bias = vec![0.0_f32; PLANE];

        let rgb = apply_ccc(&hist, &filter, &bias).unwrap();
        let norm = (rgb[0] * rgb[0] + rgb[1] * rgb[1] + rgb[2] * rgb[2]).sqrt();
        assert!((norm - 1.0).abs() < 1.0e-5);
        // The single hot bin dominates the softmax but does not saturate it, so
        // this only pins the sign of each axis: column 20 is left of centre
        // (negative u, so r > g) and row 10 is above centre (positive v).
        assert!(rgb[0] > rgb[1]);
        assert!(rgb[2] < rgb[1]);
    }

    #[test]
    fn an_exact_bin_centre_is_excluded() {
        let step = bin_step();
        let mut bins = [0_usize; 3];

        // Exactly on bin 0's centre: bin 0 itself is excluded by upstream's
        // non-zero-distance rule, and whether bin 1 survives is decided by
        // whether `-2.85 + step` rounds to within `step` — an ulp question, so
        // the test only pins the exclusion.
        let count = touched_bins(-HIST_BOUNDARY, step, &mut bins);
        assert!(!bins[..count].contains(&0));

        // Halfway between two centres: both, and only those two.
        let midpoint = -HIST_BOUNDARY + 10.5 * step;
        let count = touched_bins(midpoint, step, &mut bins);
        assert_eq!(&bins[..count], &[10, 11]);
    }
}
